### ISSUE TITLE
Question : How does it work ?

### ISSUE THREAD

**Issue by gs-akhan** [deanmcpherson/react-native-sortable-listview#1]
Hi,
It would be very interesting to know how the reordering works. I just want to know what logic does it apply when something is moved (dragged) and when do u reorder things and by what logic.
The sudo code for algorithm if written down here, it would be very informative .. 

Thanks a lot of this nice stuff ! :)

**Comment by deanmcpherson** [comment]
Hi! So reordering is controlled by the `onRowMoved` prop. This expects a function which is called whenever a row has changed position.
