### ISSUE TITLE
Android issue when using refreshControl

### ISSUE THREAD

**Issue by kevinejohn** [deanmcpherson/react-native-sortable-listview#108]
Dragging a row down (Android only) triggers the `refreshControl` and then the row gets stuck in the drag-active mode.

**Comment by nihgwu** [comment]
If you want to use refreshControl in sortable listview, you can disable the sortable listview while refreshing, also you can disable the refreshControl in the same way

**Comment by KGSachinthaU** [comment]
But how to do, I used 
onMoveStart={() => this.setState({ isDragging: true })}
onMoveEnd={() => this.setState({ isDragging: false })}

Still refresh working ? 
Help me
