### ISSUE TITLE
Is it possible to use this library into scrollview?

### ISSUE THREAD

**Issue by henrykapostel** [deanmcpherson/react-native-sortable-listview#120]
I am going to use this library to sort the data, but the phone height is too small to add some components including this. so I should use ScrollView as a parent View, and in the ScrollView, there are some components including this.
Please let me know if it is possible or not.

Thank you!

**Comment by nihgwu** [comment]
I think it's viable, you can disable the outer Scrollview when the sortable listview is activated, but it's always buggy with nesting scrolviews even not sortable
