### ISSUE TITLE
Can't apply shadow styling to SortRow on iOS

### ISSUE THREAD

**Issue by jd20** [deanmcpherson/react-native-sortable-listview#126]
Attempting to apply a shadow to the active row using sortRowStyle prop doesn't seem possible. The shadow simply doesn't appear. If I remove the `overflow: 'hidden'` from SortRow's base style, the shadow does appear, so I suspect this is an iOS/RN issue (seems described here: https://github.com/facebook/react-native/issues/449).

Any particular reason for the overflow: hidden? Would it be better to leave it off the base style, and let the end user pass it via sortRowStyle if needed? I can submit a PR if you'd like, it's a simple one-liner.

**Comment by nihgwu** [comment]
I don't know why `overflow: hidden` is there, but you can just override it in your `sortRowStyle` with `overflow: visible`

**Comment by jd20** [comment]
Ah, good point, no need to modify the original base style.
