### ISSUE TITLE
Style the non active rows when an active row exists.

### ISSUE THREAD

**Issue by TLenahan** [deanmcpherson/react-native-sortable-listview#131]
I see that the renderRow function prop has a boolean to tell if the row is active, but I am trying to apply a style to the non active rows when there is an active row, if the makes sense.

To clarify, I am trying to darken the non active rows when the user is sorting. Does anyone know how to do this, or if it is currently possible?

**Comment by nihgwu** [comment]
I think you can use `onRowActive` and `onMoveCancel`/`onMoveEnd` to achieve this

**Comment by TLenahan** [comment]
I have tried that, and the Row components are not updating unless I change shouldComponentUpdate to always return true. Is there something special I have to do?

**Comment by TLenahan** [comment]
I was able to resolve this by using PureComponent throughout index.js and removing shouldComponentUpdate
