### ISSUE TITLE
does this work with react-native 0.26.0?

### ISSUE THREAD

**Issue by masterkrang** [deanmcpherson/react-native-sortable-listview#14]
react-native 0.26.0

`
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight
} from 'react-native';

let SortableListView = require('react-native-sortable-listview');

class SortableListViewExample extends Component {
  render() {

    return (
      <View style={styles.container}>

      </View>
    );
  }
}

AppRegistry.registerComponent('SortableListViewExample', () => SortableListViewExample);
`
![image](https://cloud.githubusercontent.com/assets/452219/15450897/aa131bd4-1f5f-11e6-86b3-bc80a14ad16d.png)

**Comment by thomascrown** [comment]
Any News on this? Same thing for me

**Comment by deanmcpherson** [comment]
Hey there, PR was just accepted that should resolve this. RN 0.26 deprecated requiring react from the react-native package.
