### ISSUE TITLE
ListView will be removed by facebook

### ISSUE THREAD

**Issue by daidaishuiping** [deanmcpherson/react-native-sortable-listview#171]
ListView will be removed by facebook

**Comment by ConnectedReasoning** [comment]
Can you elaborate?

**Comment by samiede** [comment]
He means:
https://github.com/GeekyAnts/NativeBase/issues/2398

**Comment by chetstone** [comment]
This issue has been taken care of by commit https://github.com/deanmcpherson/react-native-sortable-listview/commit/061ea2719771333800d5032468f9a4f69c6b6df8
