### ISSUE TITLE
Release the deprecated list-view fix [RN 0.60+]

### ISSUE THREAD

**Issue by usrbowe** [deanmcpherson/react-native-sortable-listview#172]
Would it be possible to release master branch to `npm`.

RN 60 is out there, so it would be nice to have the fix, which was already merged in April.

For now, I'm just referring to `"deanmcpherson/react-native-sortable-listview#master"` in `package.json`.

**Comment by bargald** [comment]
@usrbowe I'm still getting 'ListView has been removed from React Native' error. How did you overcome this?

**Comment by usrbowe** [comment]
@bargald You need to double check, you really have the master branch code in your `node_modules`. Once I get code from master, it all worked well.

If you go `node_modules/react-native-sortable-listview/index.js`, can you see this 
```js
// LINE: 10
import ListView from 'deprecated-react-native-listview'
```
If not, there is problem with getting code from `master`.

Also reset your packager `yarn react-native start --reset-cache`

**Comment by chetstone** [comment]
Published to NPM just now. Thanks for the nudge.
