### ISSUE TITLE
Be able to set props to ListView

### ISSUE THREAD

**Issue by antoinerousseau** [deanmcpherson/react-native-sortable-listview#19]
I need to set `keyboardShouldPersistTaps={true}` on the returned `ListView` element, maybe we could propagate the unspecific props to it using the spread operator?
I can make a PR if needed

**Comment by deanmcpherson** [comment]
Hey @antoinerousseau, the ListView already has props spread on it. There are a few props overridden by the logic, but `keyboardShouldPersistTaps` should be passed through no problem.

**Comment by antoinerousseau** [comment]
oh yeah my bad I'm sorry I didn't see it :/
