### ISSUE TITLE
Bug in drag behavior

### ISSUE THREAD

**Issue by mosesoak** [deanmcpherson/react-native-sortable-listview#2]
I need this component! Unfortunately it's not working well for me. These are probably multiple issues but I'll just list them all here for now.

- When I drag anywhere near the bottom of the scrollable area, an extreme jitter happens. It looks like the dragged element is floating slightly to the right (try dragging down & right to repro) which creates weird horizontal gaps.
- There are bugs in the data reordering. Testing your example, just a few drags and weirdness starts happening. Spots where it clearly thinks you're dragging something you already dropped on a new drag, and gaps open up in weird places, data doesn't order correctly, etc.
- When dragging you need the view to gently scroll up or down as you approach the edge of the screen, otherwise you can't reorder except within the few tabs showing onscreen.
- When I tried to create a custom list item (it was pretty simple and copied your example's styles), dragging locks the top of the item to the touch position. That doesn't happen in your example but figured you'd want to know that it happened for me immediately when trying to integrate the component into a real project.

Thanks for your effort anyway.

**Comment by deanmcpherson** [comment]
Hey @mosesoak, thanks for your feedback. What version of RN are you using?

**Comment by mosesoak** [comment]
0.19

**Comment by deanmcpherson** [comment]
Hey @mosesoak, just released a few changes which might resolve some of the above.

**Comment by mosesoak** [comment]
Thanks!

**Comment by senthilsivanath** [comment]
Is this resolved ? Can you close this bug / confirm the items which are fixed. 

Looking to use this list view ? Is it working.

**Comment by deanmcpherson** [comment]
Closing this issues as it is reporting several distinct issues. If the issues are still occurring please submit a new issue for each, will be easier to discuss and tick off.
