### ISSUE TITLE
version 0.0.8 after dragging, scroll is not working anymore

### ISSUE THREAD

**Issue by shaniceweiwei** [deanmcpherson/react-native-sortable-listview#22]

**Comment by deanmcpherson** [comment]
Hi @shaniceweiwei, can you elaborate / provide an example?

**Comment by shaniceweiwei** [comment]
After dragging the cells (to reorder them), the whole thing can't scroll anymore.

**Comment by invig** [comment]
You need to set
```
<SortableListView
      scrollEnabled={true}
```

The latest changes are treating it as false by default.

**Comment by deanmcpherson** [comment]
Thanks @invig, should have picked up on that.
