### ISSUE TITLE
SortableListView inside ScrollView

### ISSUE THREAD

**Issue by superandrew213** [deanmcpherson/react-native-sortable-listview#23]
Is the there a way to get this to work? Currently it does not allow sorting. You can select the cell but it doesn't move. Just scrolls the parent ScrollView instead.

**Comment by CaleyD** [comment]
It works well for me on iOS. Can you share a code sample? React-native version?

**Comment by superandrew213** [comment]
onRowMoved is not being triggered

**Comment by superandrew213** [comment]
Related to this [#1046](https://github.com/facebook/react-native/issues/1046)

**Comment by deanmcpherson** [comment]
Hey @superandrew213, do you have an example of how to reproduce this?

**Comment by superandrew213** [comment]
@deanmcpherson I changed my approach and am not using the parent ScrollView anymore but it was basically like this:
```
<ScrollView>
  <SortableListView />
</ScrollView>
```

**Comment by deanmcpherson** [comment]
Hey @superandrew213, I don't think this is possible. I think you would need to disable the scroll of the scroll view for the sortable to be able to capture the move responder. You could try adding onMoveShouldSetPanResponder={true} to the PanResponder, but my suspicion is that on moving the parent scrollview will capture the event regardless.

**Comment by superandrew213** [comment]
@deanmcpherson I found a workaround by disabling the parent ScrollView onPanResponderGrant then enable onPanResponderRelease

**Comment by deanmcpherson** [comment]
Just out of curiosity, why are you nesting it inside a ScrollView?

**Comment by superandrew213** [comment]
My sortable list will only have 4 items and I have other content underneath it.

**Comment by deanmcpherson** [comment]
Ah ok, and you need it all to scroll. The content below is pretty big? Otherwise you could just render it in renderFooter.

**Comment by superandrew213** [comment]
Yeah it's quite big and includes other non sortable lists. I might try and see how it performs if I include it in renderFooter. It might rerender every time SortableListView updates

**Comment by deanmcpherson** [comment]
Yep, by default it will try and rerender every time the SortableListView updates, you can wrap it in a StaticRenderer or return false to shouldComponentUpdate to fix that though.

**Comment by deanmcpherson** [comment]
Closing issue.

**Comment by vTrip** [comment]
Found rendering elements in the header an footer very useful when wanting all content to scroll with the list and not trigger the drag. Thanks @deanmcpherson
