### ISSUE TITLE
Passing Immutable data to rows

### ISSUE THREAD

**Issue by Bhullnatik** [deanmcpherson/react-native-sortable-listview#28]
Hello,

I have an issue with last version (0.1.0). In our app we are passing down immutable data to our `(Sortable)ListView` but with last version I got an error on [this line](https://github.com/deanmcpherson/react-native-sortable-listview/blob/e59fd58f4cdd441275b199eaf7f5b4f02386b5c9/index.js#L35):

```js
One of the sources for assign has an enumerable key on the prototype chain. 
This is an edge case that we do not support. 
This error is a performance optimization and not spec compliant.

Object.assign
polyfills.js:56
Constructor.componentDidUpdate
index.js:35
```

I assume it's because Immutable uses complex data structures, which have a reference on `prototype` which is not handled by `Object.assign` React Native's polyfill ([source](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/polyfills.js#L56)).

**Comment by deanmcpherson** [comment]
Hi @Bhullnatik,

Ok, the Object.assign is only being used to take a shallow copy of row data for future comparison, which isn't be necessary at all if you are using immutable data. I've pushed a change that will only use this Object.assign if the `rowHasChanged` prop is defined. I've updated the documentation to reflect this.

I've just released 0.1.1 to npm, and . Let me know how it goes.
