### ISSUE TITLE
Add support for sections

### ISSUE THREAD

**Issue by clauderic** [deanmcpherson/react-native-sortable-listview#29]
As far as I'm aware, sections are not supported (`cloneWithRowsAndSections`, `renderSectionHeader`)? This is an important feature for most apps

**Comment by deanmcpherson** [comment]
Hi @clauderic, you are correct, sections are not currently supported. For a start we would need to change the way data is passed, and it would also add additional complexity to dragging logic, and sorting logic (e.g. section 2, item 3 is dragged to section 1 item 2).

I'm happy to review pull requests, but I don't think there is a strong enough need to warrant the additional complexity.
