### ISSUE TITLE
Android: adjacent rows change positions not smoothly when dragging

### ISSUE THREAD

**Issue by o-khizhnyak** [deanmcpherson/react-native-sortable-listview#31]
Unlike iOS demo, when running example.js on Android, inactive rows change theirs positions without any animation when active item is dragging.

Using react-native 0.30.0, react-native-sortable-listview 0.1.1, Android 5.0.1.

![sortable-listview-android](https://cloud.githubusercontent.com/assets/3727309/17830808/dd6992e8-66df-11e6-900c-db95b9624954.gif)

**Comment by uc-des** [comment]
Hello o-khizhnyak 
I am not able to drop the component to specific place 
Using Android

**Comment by deanmcpherson** [comment]
Hi @o-khizhnyak, the animation on iOS is purely powered by LayoutAnimation. If you have LayoutAnimation enabled it may work also on android (see https://github.com/facebook/react-native/issues/5267).

**Comment by o-khizhnyak** [comment]
Thanks, @deanmcpherson, it works!
Enabling of LayoutAnimation solved this problem.
