### ISSUE TITLE
How to pass props other than 'data'?

### ISSUE THREAD

**Issue by thomaswright** [deanmcpherson/react-native-sortable-listview#32]
Other than the initial render and the row data props, props passed to the renderRow function don't seem to update.

**Comment by deanmcpherson** [comment]
Hey @thomaswright, try defining your own `rowHasChanged`. For performance reasons, we can't just re-render the row every time setState is called.

**Comment by thomaswright** [comment]
Okay, thanks @deanmcpherson, just checking :)

**Comment by Twansparant** [comment]
Could you post an example of this? I'm running into the same problem.
Thanks!

**Comment by thomaswright** [comment]
Hi @Twansparant. I never got around to writing my own rowHasChanged and instead just stopped using this library. Would be interesting though - share if you do!
