### ISSUE TITLE
Not able to Sort the component

### ISSUE THREAD

**Issue by uc-des** [deanmcpherson/react-native-sortable-listview#33]
I want a sortable component, I am able to drag but while dropping it return back to its original position how to make it stay in the position where it has been dropped

**Comment by deanmcpherson** [comment]
Hi @uc-des, you will need to correctly define `onRowMoved` to represent the new order of the data for the drop to stay.

**Comment by uc-des** [comment]
Hi deanmcpherson

Thanks for your response
I am trying to define  onRowMoved but not able to do it can you please help me out.
