### ISSUE TITLE
Is it possible to adjust hold delay as an option variable?

### ISSUE THREAD

**Issue by joonhocho** [deanmcpherson/react-native-sortable-listview#37]
For example, I want to reduce the hold delay so that the sorting initiates more quickly.

**Comment by deanmcpherson** [comment]
HI @joonhocho, you can set delayLongPress to whatever you like on the Touchable element that has the sortHandlers on them in the row. See https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html for details.
