### ISSUE TITLE
Oftentimes the same rows are cloned and appear multiple times.

### ISSUE THREAD

**Issue by joonhocho** [deanmcpherson/react-native-sortable-listview#44]
I don't know exactly how to replicate this, but when I sort things around, some row gets copied and I can see multiple of them.
Any thoughts? or anyone having the same issue?

**Comment by deanmcpherson** [comment]
Hi @joonhocho I've recently seen something like this on newer versions of RN on Android. Is that where you experienced it?

**Comment by joonhocho** [comment]
@deanmcpherson I had it on iOS emulator and real device. I guess it's universal.

**Comment by chetstone** [comment]
Should be fixed by f5c2ae0cc55f3d8c332ee3ba5b8d3eb568520739. Please reopen if not.
