### ISSUE TITLE
Access row's index from inside row component

### ISSUE THREAD

**Issue by logileifs** [deanmcpherson/react-native-sortable-listview#47]
How would one access the index of a row from inside a RowComponent instance?

For example, if I were to add a button to my row and one that button is pressed I would like to know where in the order array the pressed row is.

How would one accomplish that?

**Comment by deanmcpherson** [comment]
Hi @logileifs, in the renderRow function, I believe the third argument is the row's index.

**Comment by ippa** [comment]
Nice, but if I display out that number inside the RowComponent it's not updated when I reorder the rows? Basically I wan't to display #1, #2, #3, etc.. in each RowComponent

**Comment by chetstone** [comment]
@ippa I'm also finding that the index is not updated when the rows are reorder, so I just define
```
rowHasChanged={(r1,r2) => {return true}}
```
I have a short list, so it should be OK.

**Comment by chetstone** [comment]
Closing, inactive.
