### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by rick-li** [deanmcpherson/react-native-sortable-listview#5]
example doesn't work in android.

**Comment by andpor** [comment]
Yes , seems like the plugin does not work on Android at all..using RN 0.22...

**Comment by deanmcpherson** [comment]
Hey guys, I'm tied down with work for the next few weeks so won't be able to work on adding android support. There shouldn't be much getting in the way of android support working though as it's all js. PRs welcome :)

**Comment by deanmcpherson** [comment]
Hey @rick-li,

I just accepted and released a PR that ads android support. Note that the module relies on LayoutAnimation, which needs to be enabled on Anrdroid with:

```
var {UIManager} = require('react-native');
UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);```
