### ISSUE TITLE
having a header or section header mess up the position calculation

### ISSUE THREAD

**Issue by ravelab** [deanmcpherson/react-native-sortable-listview#50]
If I have a header that is about 2x the row itemHeight, when I drag a row to position 3, it seems to think I'm dragging to position 4.  How do I account for the header height in the code?  Thanks

**Comment by mamidala** [comment]
Am too facing same issue.

**Comment by milesibastos** [comment]
May you provide some code to reproduce this case?

**Comment by chetstone** [comment]
Should be fixed by f5c2ae0cc55f3d8c332ee3ba5b8d3eb568520739

**Comment by femiveys** [comment]
I have the same problem.

With a header, the dragging is wrong. When dragging the first item, it starts where the first item should be. Same for the second and so on.

How should I solve this?

I am on version 0.2.2
