### ISSUE TITLE
Animation quality disappointing

### ISSUE THREAD

**Issue by chetstone** [deanmcpherson/react-native-sortable-listview#51]
I have the same issue as #48 and in addition, it is difficult to "grab" an item to start dragging it. I usually have to press and hold several times before the item starts to move.

And then, whenever I drag an item to or from the first row, the item behind starts rapidly bouncing up and down, as shown in this gif:

![rn-sortable](https://cloud.githubusercontent.com/assets/976343/20541975/b48236c4-b0bc-11e6-87e9-506a997c475f.gif)

Probably it will be necessary to leverage Android native animations to fix these issues. I use [react-native-tableview](https://github.com/aksonov/react-native-tableview) on iOS which works great.

I'm using react-native 0.32.1 and 0.1.1 (as modified by PR #49) of this component.

**Comment by milesibastos** [comment]
:cry: PR are welcome!
