### ISSUE TITLE
TouchableHighlights Undefined

### ISSUE THREAD

**Issue by felangga** [deanmcpherson/react-native-sortable-listview#59]
I found an error when compiled with RN 0.40, the error said undefined is not an object (evaluating 'this.wrappedInstance.setNativeProps).

When I remove  {...this.props.sortHandlers} from TouchableHighlights, the error disappears, but I can't drag&drop the row

**Comment by DannyAziz** [comment]
I get a similar issue, the error message I get is `Cannot read property 'setNativeProps' of undefined`.

I realised I think It may have to do with the child of TouchableHighlight. When using a Card component from [NativeBase](http://nativebase.io/) I get the error, when just using `<Text>` then everything works

**Comment by DannyAziz** [comment]
Worked it out, wrap whatever components you have inside `<TouchableHighlight>` inside a `<View>` as per the note on the [documentation](https://facebook.github.io/react-native/docs/touchablehighlight.html). This fixed it for me, hopefully, it works for you @felangga

**Comment by chetstone** [comment]
Closing, solution found.
