### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by jdmunro** [deanmcpherson/react-native-sortable-listview#6]
I've noticed a couple of issues with the scrolling using a modern version of React Native (0.24.1). The first issue is that there are some deprecation/yellow box warnings, which should be easy enough to fix (see gif).

The second and more important issue is that you can make the scroll view scroll to an incorrect offset. I haven't worked out the exact steps to reproduce this. I usually just drag some items around a bit and more often than not the items will appear to scroll to the bottom of the screen. See the gif for an example. It seems more likely to happen when there are fewer items in the list view.

![reorder-bug](https://cloud.githubusercontent.com/assets/17656/14916922/387853d8-0e14-11e6-91c5-ad738bf5caa0.gif)

**Comment by deanmcpherson** [comment]
Hey @jdmunro, just released an update which fixes the warning, and potentially the snapping issue as well.

**Comment by jdmunro** [comment]
Great, thanks! I'll give that a try and let you know how it goes.

**Comment by jdmunro** [comment]
I've tested this out now and both issues seem to be resolved. Thanks for fixing them so quickly.
