### ISSUE TITLE
Specifying a sort handle

### ISSUE THREAD

**Issue by joncursi** [deanmcpherson/react-native-sortable-listview#60]
Is it possible to specify a specific element that should be used as the sorting handle? Right now, the entire item within `renderRow` is used to respond to the sort presses, however this blocks other pointer events that the row item may have. Would be great if you could target a specific element on each renderRow item that the touch mechanism should attach to, to keep other pointer events available.

**Comment by joncursi** [comment]
Here's a practical example. Would be great if the handle element in particular could be specified, but leave the rest of the row item alone because it has it's own touch events:

![screen_shot_2017-02-24_at_7_34_46_pm](https://cloud.githubusercontent.com/assets/4974609/23326104/a302ec26-fac8-11e6-9faf-69f9495bb056.png)

---
---
---

![screen_shot_2017-02-24_at_7_35_45_pm](https://cloud.githubusercontent.com/assets/4974609/23326105/a484c420-fac8-11e6-9a23-faf320baa0a9.png)

**Comment by joncursi** [comment]
Seems like if you chunk up the row item into a series of TouchableWithoutFeedback's aligned with flex, you can get around this by disabling / enabling each touchable selectively based on state:

```jsx
        <TouchableWithoutFeedback
          disabled={!promptIsOpen}
          onPress={() => onPromptToggle()}
        >
          ...
        </TouchableWithoutFeedback>
        <TouchableWithoutFeedback
          disabled={promptIsOpen}
          onPress={() => somethingElse()}
        >
          ...
        </TouchableWithoutFeedback>
```

**Comment by JeroenNelen** [comment]
hello @joncursi I am trying something similar, part of the row should trigger other actions and only the right part (as indicated to your screenshots) should enable the dragging. Do you have any more info on how you fixed you situation or any more extensive code example somewhere?

Kind regards,

**Comment by joncursi** [comment]
@jeroennelen I haven't made any additional progress aside from the comments made here.

**Comment by carllippert** [comment]
Truthfully I have not been able to make a row respond but have managed to make a handle respond just fine. If you can tell me why a row would not work in relation to styling ( as far as i can tell ) please let me know. 

`class RationIngredientRow extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {

    const { dispatch } = this.props;
    const { data } = this.props;
    debugger;
    return ( 
                (data.editing)
                 ?
                <View style={styles.editingRowContainer}>

                  <View style={styles.topRow}>

                    <View style={styles.ingredientName}>
                      <Text style={styles.ingredientNameText}> {data.name} </Text>
                    </View>
                    <TouchableOpacity 
                    style={styles.subtractButton}
                    onPress={() => {
             
                        dispatch(subtractErrorFromRationIngredient(data.ingredientID));
                    }}
                    >
                      <Icon
                        name={"md-remove"}
                        size={20}
                        color={'white'}
                      />
                    </TouchableOpacity>
                    <View style={styles.ingredientWeight}>
                      <Text style={styles.ingredientWeightText}> {data.weightTotal.toFixed(0)} </Text>
                    </View>
                    <TouchableOpacity 
                    style={styles.addButton}
                    onPress={() => {
                        dispatch(addErrorFromRationIngredient(data.ingredientID));
                    }}>
                      <Icon
                        name={"md-add"}
                        size={20}
                        color={'white'}
                      />
                    </TouchableOpacity>
                    <View style={styles.ingredientWeightSum}>
                      <Text style={styles.ingredientWeightSumText}> {data.weightSum.toFixed(0)} </Text>
                    </View>

                  </View>
                  <View style={styles.bottomRow}> 
                    <TouchableOpacity
                      style={styles.sortButton}
                      {...this.props.sortHandlers}
                      >
                        <Image
                        source={require('../../images/reorder.png')}
                        style={{width:20, height: 27}}
                        />
                    </TouchableOpacity>
                    <TouchableOpacity 
                      style={styles.cancel}
                      onPress={() => {
                        //cancel button
                        dispatch(cancelErrorUpdateforRationIngredient(data.ingredientID));
                      }}>
                        <Text style={styles.cancelText}> CANCEL </Text>

                      </TouchableOpacity>
                      <TouchableOpacity 
                      style={styles.save}
                      onPress={() => {
                        //save button
                        dispatch(saveErrorUpdateForRationIngredient(data));
                      }}>
                        <Text style={styles.saveText}> SAVE </Text>
                        
                      </TouchableOpacity>
                  </View>
                </View>
                :
                <View>
                <TouchableOpacity
                 style={styles.rowContainer}
                 onPress={()=>{
                   if(this.props.confirmed == true)
                   {
                      dispatch(editIngredientForRation(data.ingredientID));
                   }
                 }} >
                  <View style={styles.ingredientName}>
                        <Text style={[styles.ingredientNameText, styles.regularText]}> {data.name} </Text>
                  </View>
                  <View style={[styles.ingredientWeight, styles.regularText]}>
                      <Text style={styles.ingredientWeightText}> {data.weightTotal.toFixed(0)} </Text>
                  </View>
                  <View style={[styles.ingredientWeightSum, styles.regularText]}>
                      <Text style={styles.ingredientWeightSumText}> {data.weightSum.toFixed(0)} </Text>
                  </View>
                </TouchableOpacity>
                <View style={styles.separator} />
                </View>
               
    );
  }
}`

![image](https://cloud.githubusercontent.com/assets/16457876/25393772/f7673a1c-29a1-11e7-8104-5526c9b6d57b.png)

![image](https://cloud.githubusercontent.com/assets/16457876/25393810/0d7ea466-29a2-11e7-8d81-e8e848260b73.png)

**Comment by chetstone** [comment]
See also #85
