### ISSUE TITLE
disableSorting doesn't work

### ISSUE THREAD

**Issue by gsavvid** [deanmcpherson/react-native-sortable-listview#62]
Hello,

It seems like `disableSorting` is not working. I'm following the example code and when setting `disableSorting={true}` nothing changes. The only way I've found for disabling the sorting is to remove `{...this.props.sortHandlers}` from the row component. I've only tried this on Android.

Any ideas? Thanks in advance!

**Comment by SmallMouth** [comment]
hi,
I have same problem.

**Comment by chetstone** [comment]
@gsavvid, @SmallMouth , can you try with the latest version? If it still doesn't work, could you please submit some example code demonstrating the problem? I've added a button for disabling and enabling sorting to the Sortable example app [in this branch.](https://github.com/chetstone/react-native-sortable-listview/tree/disable_button)
Works for me.

**Comment by foggy1** [comment]
It does not work for me either.  I can't share a code sample right this minute, but I'm going to take a look at the source code when I get a chance.  I'm in iOS, and I'm not spreading the entire sortHandler out in the row component's touchable highlight.

**Comment by SmallMouth** [comment]
@chetstone 
on this issue , I use version 0.1.1 and it does not work. now I update to version 0.2.2, it can work!!!
my example code :
- [v0.1.1
](https://github.com/SmallMouth/react-native-sortable-listview) fail
- [v0.2.2
](https://github.com/SmallMouth/react-native-sortable-listview/tree/disableSorting) pass

**Comment by chetstone** [comment]
Cool! Thanks for reporting!
