### ISSUE TITLE
Unwanted scrolling

### ISSUE THREAD

**Issue by chetstone** [deanmcpherson/react-native-sortable-listview#64]
When a long list has been scrolled down some distance from the top, and an item near the top of the list is selected with a long press for sorting, the list scrolls back to the top without the user dragging the item towards the top.

Here is a demo.

![untitled](https://cloud.githubusercontent.com/assets/976343/23723637/225770b8-0407-11e7-916a-a3afee128f3c.gif)

**Comment by chetstone** [comment]
A review of the Sortable app operation shows the following problems (which may be more serious than the one documented above) still remain.
 
1. On iOS, when trying to drag an item from the middle of a long list to the top or bottom, the list does not scroll, or scrolls extremely slowly, so that you can't get it where you want. Android works better.

2. On Android, when you try to drag an item to the very bottom of a long list, there is a lot of jitter when you try to cross the bottom item. This was first noticed in issue #2.

2. On Android, when you drag an item from the middle of a long list to the bottom and then back up, the open slot no longer lines up with the image of the active item.

**Comment by sachinB94** [comment]
Hey, any update on this "Unwanted Scroll" issue? I'm still facing it.

**Comment by chetstone** [comment]
PR #93 doesn't really fix the initial issue reported here, at least on Android. On iOS it improves it somewhat: instead of scrolling all the way to the top, the superior element just drops down below the grabbed element.

I may have made a mistake in documenting several issues here. Of the three issues I mention in my comment [above](https://github.com/deanmcpherson/react-native-sortable-listview/issues/64#issuecomment-312464925), only the second is affected: It is greatly improved by PR #93 but there is still some jitter if the list is scrolled all the way to the bottom when the sort is started. But it is a big help for what is for me probably the most important of these four issues.

**Comment by chetstone** [comment]
Ah but good news is that PR #95 does fix the initial "unwanted scroll" issue.

**Comment by nihgwu** [comment]
😀
