### ISSUE TITLE
Is it possible to have a delete feature on the row?

### ISSUE THREAD

**Issue by bevinthomas** [deanmcpherson/react-native-sortable-listview#68]

**Comment by chetstone** [comment]
You might be able to use SwipeRow from react-native-swipe-list-view with version 0.2.2 of this component. See Issue #58

**Comment by MossP** [comment]
SwipeRow works well this component on iOS. Doesn't play so nicely on Android though. Having said that; I see more errors on the Android side of things in this component anyway.
