### ISSUE TITLE
strange behaviour when I drag and scroll down

### ISSUE THREAD

**Issue by aknad** [deanmcpherson/react-native-sortable-listview#76]
In addition to [this](https://github.com/deanmcpherson/react-native-sortable-listview/issues/64) unwanted scroll there's another strange behavior
If I drag an element to the bottom, when the scroll starts I lose the control and it continues to scrolls until it reaches the end of the list and while it scrolls I can do nothing

![sortablelist](https://cloud.githubusercontent.com/assets/7056879/25526076/3d0cee82-2c12-11e7-8d3e-ad0465856fff.gif)

**Comment by aknad** [comment]
the same thing happens also scrolling up

**Comment by MossP** [comment]
I've also noticed this but only recently so I think it may be something in my code that has caused it (I've recently wrapped the component in other views to offset the layout issues).

**Comment by andres-torres-marroquin** [comment]
I removed width: '100%', from a inner element: ![](https://www.dropbox.com/s/y152ur8wvskmpcx/Captura%20de%20pantalla%202017-05-17%2011.58.45.png?dl=1)

**Comment by sajsanghvi** [comment]
Any solutions for this? having the same issue as well

**Comment by marstall** [comment]
@aknad i am trying to implement the 3-line grabber controls you have there - can you offer any tips or code as to how you did that? Did you use an onPressIn new sortHandler?

**Comment by aknad** [comment]
@marstall 
We have decided not to use this package because of this bug and other unexpected behaviours
Unfortunately I can't find my old code but I remember that the first <Touchable*> in the structure is used to manage the drag

**Comment by marstall** [comment]
@aknad thanks for the reply. what did you end up using?

**Comment by aknad** [comment]
We are thinking to add a "vintage" solution with up and down arrows
Not so good for the UX but it works

**Comment by adrienthiery** [comment]
After fighting a lot with that lib, I went for https://github.com/gitim/react-native-sortable-list. I strongly advise you to get that one!
