### ISSUE TITLE
Scroll not working on Android

### ISSUE THREAD

**Issue by Deevent** [deanmcpherson/react-native-sortable-listview#79]
Hello,

I'm not able to scroll down the list if it's bigger than the screen. It's working fine on iOS but not on Android. I've tried to set scrollEnabled={true} but no chance.

My code is just a < SortableListView > :

> <SortableListView
                    scrollEnabled={true}
                    order={order}
                    onRowMoved={e => {
                        order.splice(e.to, 0, order.splice(e.from, 1)[0]);
                        this.props.newPlaylistOrder(params.playlistId, order)
                    }}
                    style={{flex: 1}}
                    contentContainerStyle={styles.contentContainer}
                    data={this.props.playlists[params.playlistId].videos}
                    renderRow={row => <RowComponent song={row} />}
                />

What can be the cause of that behavior ?

Thanks for the great component

**Comment by chetstone** [comment]
Try the Sortable example and see if that works for sorting on android (it should). Then see if you can find the difference between the example and your code.
