### ISSUE TITLE
Dragging not working

### ISSUE THREAD

**Issue by mocanSergiu666** [deanmcpherson/react-native-sortable-listview#83]
on longPress nothing happens :   (
Therefore I can not perform sorting by drag and drop ::: (

**Comment by vTrip** [comment]
Could you post a code snippet of your implementation?

Quick tip: Make sure your `TouchableHighlight` tag is a the highest most position

**Comment by mocanSergiu666** [comment]
The problem was that I haven't used TouchableHighlight at all. At thirst I didn't know that I must embed items in TH. Suddenly I have observed this and fixed it. But thanx anyway.
