### ISSUE TITLE
checkPropTypes has been moved to a separate package.

### ISSUE THREAD

**Issue by iamaluckyman** [deanmcpherson/react-native-sortable-listview#88]
Warning:
checkPropTypes has been moved to a separate package.
Accessing React.checkPropTypes is no longer supported 
and will be removed completely in React 16.
![default](https://user-images.githubusercontent.com/24911989/27816563-3e88a96a-60c7-11e7-944e-9f84f013fd4e.png)

**Comment by oliviachang29** [comment]
+1: this warning is getting annoying

**Comment by chetstone** [comment]
I've seen this warning when running the jest tests and it's mentioned in the readme. Are you seeing it in apps?

If so, please mention the versions you're using. (React, react native and this component)

And as always, PRs are welcome.

**Comment by nihgwu** [comment]
That's irrelevant with this component, it's a warning form the core components from react-native
