### ISSUE TITLE
scrollToEnd

### ISSUE THREAD

**Issue by k4ch0w** [deanmcpherson/react-native-sortable-listview#90]
Hey, I am new to react native and I saw that you define a function for scrollTo within the class but I am not sure how to call it from the parent. I am trying to have the listview stay at the bottom element.

**Comment by nihgwu** [comment]
`<SortalbleListView ref="sortableList" />`
then call `this.sortableList.list.refs.list.scrollToEnd()`

**Comment by k4ch0w** [comment]
Thank you @nihgwu!

For anyone else having this same issue the code was

`<SortableListView
                    ref={(sortableListView) => { this.sortableListView= sortableListView; }} />
if(this.sortableListView) {
            this.sortableListView.refs.list.scrollToEnd()
}`
