### ISSUE TITLE
Warning: SortableListView: isMounted is deprecated

### ISSUE THREAD

**Issue by akshitharamachandran** [deanmcpherson/react-native-sortable-listview#91]
I npm installed this package and it works as desired. I do, however, receive the following warning message when I move rows within the list: 

 "Warning: SortableListView: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks."

Any solutions would be greatly appreciated. Thanks!

**Comment by nihgwu** [comment]
try the latest version, there is no `isMounted` anymore
